In [1]:
import cv2
import numpy as np

In [2]:
s = "image\\"
num = 100
row = 240
col = 240
a = np.zeros((num, row, col))
print(a.shape)

(100, 240, 240)


In [3]:
n = 0
for i in range(0, 10):
    for j in range(1, 11):
        a[n, :, :] = cv2.imread(s + str(i) + "\\" + str(i) + "-" + str(j) + ".bmp", 0)
        n = n+1
print(a[0, ::])

[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [10]:
print(a[0,::].shape)

(240, 240)


In [9]:
feature=np.zeros((num,round(row/5),round(col/5)))
for ni in range(0,num):
    for nr in range(0,row):
        for nc in range(0,col):
            if a[ni,nr,nc]==255:
                feature[ni,int(nr/5),int(nc/5)]+=1
f=feature

In [12]:
o=cv2.imread("image\\test\\5.bmp",0)
of=np.zeros((round(row/5),round(col/5)))
for nr in range(0,row):
    for nc in range(0,col):
        if o[nr,nc]==255:
            of[int(nr/5),int(nc/5)]+=1

In [17]:
d=np.zeros(100)
for i in range(0,100):
    d[i]=np.sum((of-f[i,:,:])*(of-f[i,:,:]))
print(d)
d=d.tolist()
temp=[]
Int = max(d)
print(Int)
k=7
for i in range(k):
    temp.append(d.index(min(d)))
    d[d.index(min(d))] = float('inf')
print(temp)

[  96066.   85142.  110285.  110153.  102270.  103889.  103948.  100054.
  112656.   99778.   86995.   84424.   84677.   83273.   82476.   82803.
   83868.   82677.   84338.   84269.   95855. 1333586.   91477.  102119.
  107335.  105874.  108784.  111414.  114757.  112354.   79948.   97797.
  107031.   78375.   85575.  107129.  111396.  105933.  116503.  112122.
  108857.  106114.  102126.  103560.  101034.  105016.  111375.  110900.
  110628.  108814.   87223.   87918.   95230.   88730.   79073.   82151.
   94188.   86252.   77185.   91800.   88331.  108362.  121314.   89836.
  143935.  108946.  109578.   97324.   99419.  120538.  102910.  102939.
  100465.  102443.   97068.   88816.  106088.  100535.  101622.  104550.
  117031.  122261.  118118.  127061.  125294.  111937.  128592.  108484.
  109604.  122142.  112495.  112658.  114000.  106094.  101869.  114693.
  127703.  109004.  105606.  117819.]
1333586.0
[58, 33, 54, 30, 55, 14, 17]


In [18]:
temp=[i/10 for i in temp]
r=np.zeros(10)
for i in temp:
    r[int(i)]+=1
print("當前的數字可能為:"+str(np.argmax(r)))

當前的數字可能為:5


In [29]:
train = feature[:,:].reshape(-1,round(row/5)*round(col/5)).astype(np.float32)
trainLabels = [int(i/10)  for i in range(0,100)]
trainLabels=np.asarray(trainLabels)
print(*trainLabels)

0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9
