In [3]:
import cv2
import numpy as np

In [4]:
s = "image\\"
num = 100
row = 240
col = 240
a = np.zeros((num, row, col))
print(a.shape)

(100, 240, 240)


In [5]:
n=0
for i in range(0,10):
    for j in range(1,11):
        a[n,:,:]=cv2.imread(s+str(i)+"\\"+str(i)+"-"+str(j)+".bmp",0)
        n+=1

In [6]:
print(a[0,::])

[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


In [7]:
print(a[0,::].shape)

(240, 240)


In [8]:
feature=np.zeros((num,round(row/5),round(col/5)))
for ni in range(0,num):
    for nr in range(0,row):
        for nc in range(0,col):
            if a[ni,nr,nc]==255:
                feature[ni,int(nr/5),int(nc/5)]+=1

In [9]:
o=cv2.imread("image\\test\\5.bmp",0)
of=np.zeros((round(row/5),round(col/5)))
for nr in range(0,row):
    for nc in range(0,col):
        if o[nr,nc]==255:
            of[int(nr/5),int(nc/5)]+=1

In [10]:
train= feature[:,:].reshape(-1,round(row/5)*round(col/5)).astype(np.float32)
print(train.shape)
trainLabels=[int(i/10) for i in range(0,100)]
trainLabels=np.asarray(trainLabels)
print(*trainLabels)
print(type(trainLabels))

(100, 2304)
0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 8 8 8 8 8 8 8 8 8 8 9 9 9 9 9 9 9 9 9 9
<class 'numpy.ndarray'>


In [11]:
o=cv2.imread("image\\test\\5.bmp",0)
of=np.zeros((round(row/5),round(col/5)))
for nr in range(0,row):
    for nc in range(0,col):
        if o[nr,nc]==255:
            of[int(nr/5),int(nc/5)]+=1

In [12]:
test=of.reshape(-1,round(row/5)*round(col/5)).astype(np.float32)
knn=cv2.ml.KNearest_create()
knn.train(train,cv2.ml.ROW_SAMPLE, trainLabels)
ret,result,neighbours,dist = knn.findNearest(test,k=7)
print("當前隨機數可以判定為類型：", result)
print("距離當前點最近的7個鄰居是：", neighbours)
print("7個最近鄰居的距離 : ", dist)

當前隨機數可以判定為類型： [[5.]]
距離當前點最近的7個鄰居是： [[5. 3. 5. 3. 5. 1. 1.]]
7個最近鄰居的距離 :  [[77185. 78375. 79073. 79948. 82151. 82476. 82677.]]
